services:
  comprofix:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/comprofix/comprofix.com:${IMAGE_TAG}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${HOSTNAME}`) || Host(`www.${HOSTNAME}`)
      - traefik.http.routers.${CONTAINER_NAME}.entrypoints=https
      - traefik.http.routers.${CONTAINER_NAME}.tls=true
      - traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=80

networks:
  proxy:
    external: true
